#!/bin/sh

echo "*********************************************************"
echo "*                                                       *"
echo "* Jedi Maker Xtream                                     *"
echo "* by KiddaC (c) 2018/2019                               *"
echo "*                                                       *"
echo "* Restart Enigma-2 GUI to add plugin into plugin list*"
echo "*********************************************************"
sleep 5
exit 0
