#!/bin/sh
rm -rf /etc/enigma2/jediplaylists/playlist_all.json > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/JediMakerXtream > /dev/null 2>&1
rm -rf /etc/enigma2/*jmx*.* > /dev/null 2>&1
rm -rf /etc/epgimport/*jmx*.* > /dev/null 2>&1
sed -i '/jmx/d' /etc/enigma2/bouquets.tv
echo "Restart GUI to finish uninstall!"
sleep 10
exit 0
